# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM install cache
      uses: c-hive/gha-npm-cache@v1
    - name: Setup and Install
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Run Unit Tests
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    - name: Run E2E Tests
      run: npm run e2e -- --protractor-config=projects/test-app/e2e/protractor-ci.conf.js
